# Generated by Django 4.0.4 on 2022-05-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrow',
            name='status',
            field=models.CharField(blank=True, choices=[('REGISTERED', 'Registered'), ('NOT_READY', 'Vehicle awaiting for diagnostic'), ('IN_PROCESS', 'Vehicle is being repaired'), ('READY', 'Fixed, ready to be returned')], default='REGISTERED', help_text='STATUS', max_length=15),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Enter price')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Ready by')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.car')),
                ('service', models.ManyToManyField(through='car_service.OrderRow', to='car_service.service')),
            ],
        ),
        migrations.AddField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.order'),
        ),
    ]
