# Generated by Django 4.0.4 on 2022-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0002_orderrow_status_order_orderrow_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('REGISTERED', 'Registered'), ('NOT_READY', 'Vehicle awaiting for diagnostic'), ('IN_PROCESS', 'Vehicle is being repaired'), ('READY', 'Fixed, ready to be returned')], default='REGISTERED', help_text='STATUS', max_length=15),
        ),
    ]
