# Generated by Django 4.0.4 on 2022-05-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0006_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'Registered'), ('a', 'Vehicle awaiting for diagnostic'), ('br', 'Vehicle is being repaired'), ('f', 'Fixed, ready to be returned')], default='r', help_text='STATUS', max_length=15),
        ),
    ]
