# Generated by Django 4.0.4 on 2022-06-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0008_carmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='photo_link',
            field=models.CharField(default='', max_length=330, verbose_name='Link to photo'),
        ),
    ]
