# Generated by Django 4.0.4 on 2022-06-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0009_carmodel_photo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000, verbose_name='Aprašymas'),
        ),
    ]
