# Generated by Django 4.0.5 on 2022-06-12 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_service', '0014_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='car_service.car'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='order_rows', to='car_service.order'),
        ),
        migrations.AlterField(
            model_name='orderrow',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='car_service.service'),
        ),
    ]
